### PR TITLE
LICENSE: add BSD 3 clause

### PR DESCRIPTION
**Pull request by philips**
based on some of your other projects I added a 3 clause license.

### CODE REVIEW

**Comment by philips** [comment]
Hello @remyoudompheng -

I wanted to work on fixing up this library a bit but it doesn't have any license that I can find. I looked at your other code and it looks like you prefer the 3 clause BSD license so I added it.

I hope that this works for you.

Thanks!

Brandon

**Comment by vmarmol** [comment]
:+1:

**Comment by rjnagal** [comment]
:+1: I am trying to use this library in google/cadvisor. Having a license would make it easier to use :)

Thanks.

**Comment by philips** [comment]
ping

**Pull request closed without merging**
